### ISSUE TITLE
robots dont work

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedRobots#12]
i bought your plugin robots over a month ago and since then havent been able to use it really. The miner dont transfer items to hopper, and the fisher dont fish. could we please get a fix on these 2 robots?

06.02 12:59:07 [Server] Server thread/WARN [AdvancedRobots] Task #115 for AdvancedRobots v1.2.2 generated an exception
06.02 12:59:07 [Server] INFO java.lang.IllegalArgumentException: Material cannot be null
06.02 12:59:07 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:70) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:58) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:36) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at gc.advancedrobots.utils.FishingUtils.getRandomFish(FishingUtils.java:16) ~[?:?]
06.02 12:59:07 [Server] INFO at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:149) ~[?:?]
06.02 12:59:07 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
06.02 12:59:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

i cant find an error with the miner, he just dont work.

the y both use the fuel you give them but they dont work

**Comment by GC-spigot** [comment]
Try the new update
