### ISSUE TITLE
Null pointer on robot task

### ISSUE THREAD

**Issue by ICEconchy** [GC-spigot/AdvancedRobots#13]
https://hastebin.com/wimupilebo.bash

Server version: 1.15.2
AR version: 1.2.3

Recreatable when robot is placed on a hopper and given fuel then a task.... The robots are unuseable

**Comment by ICEconchy** [comment]
When joining a server in different world null appears

https://hastebin.com/hisolecabe.pl

**Comment by GC-spigot** [comment]
Should be fixed now!

**Comment by ICEconchy** [comment]
It isn't the plugin doesn't work

https://hastebin.com/afonetimum.sql
