### ISSUE TITLE
Will not load on 1.14

### ISSUE THREAD

**Issue by 7SINS7** [GC-spigot/AdvancedRobots#9]
30.12 17:38:58 [Server] Server thread/WARN [AdvancedRobots] Task #371 for AdvancedRobots v1.1.5 generated an exception
30.12 17:38:58 [Server] INFO java.lang.NullPointerException: null
30.12 17:38:58 [Server] INFO at gc.advancedrobots.robots.RobotSettings.getRobotsAvailableToWork(RobotSettings.java:116) ~[?:?]
30.12 17:38:58 [Server] INFO at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:129) ~[?:?]
30.12 17:38:58 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:38:58 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:38:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Multicraft] Skipped 40 lines due to rate limit (30/s)
30.12 17:39:01 [Server] Server thread/WARN [AdvancedRobots] Task #370 for AdvancedRobots v1.1.5 generated an exception
30.12 17:39:01 [Server] INFO java.lang.NullPointerException: null
30.12 17:39:01 [Server] INFO at gc.advancedrobots.robots.RobotSettings.getRobotsAvailableToWork(RobotSettings.java:116) ~[?:?]
30.12 17:39:01 [Server] INFO at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:108) ~[?:?]
30.12 17:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
30.12 17:39:01 [Server] Server thread/WARN [AdvancedRobots] Task #371 for AdvancedRobots v1.1.5 generated an exception
30.12 17:39:01 [Server] INFO java.lang.NullPointerException: null
30.12 17:39:01 [Server] INFO at gc.advancedrobots.robots.RobotSettings.getRobotsAvailableToWork(RobotSettings.java:116) ~[?:?]
30.12 17:39:01 [Server] INFO at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:129) ~[?:?]
30.12 17:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
30.12 17:39:01 [Server] Server thread/WARN [AdvancedRobots] Task #372 for AdvancedRobots v1.1.5 generated an exception
30.12 17:39:01 [Server] INFO java.lang.NullPointerException: null
30.12 17:39:01 [Server] INFO at gc.advancedrobots.robots.RobotSettings.getRobotsAvailableToWork(RobotSettings.java:116) ~[?:?]
30.12 17:39:01 [Server] INFO at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:49) ~[?:?]
30.12 17:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:01 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
30.12 17:39:04 [Multicraft] Skipped 25 lines due to rate limit (30/s)
30.12 17:39:04 [Server] Server thread/WARN [AdvancedRobots] Task #370 for AdvancedRobots v1.1.5 generated

**Comment by artecblade** [comment]
This is the plugin i bought from spigot - artecblade, same server we both run.

**Comment by GC-spigot** [comment]
Fixed
